version: "3"

services:
  server:
    build: 
      context: ./server
    environment:
      - PORT=4000
      - VIRTUAL_HOST=2000
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/server/src
    command: node src/server.js
    restart: always
  client:
    build: 
      context: ./client
    ports:
      - 80:80
      - 443:443
    links:
      - server
    restart: always

